### ISSUE TITLE
Pause running program functionality

### ISSUE THREAD

**Issue by mheyer32** [bebbo/bgdbserver#1]
Am I right to assume that the current gdbserver is not able to stop a running program (except through setting breakpoints) ?

I thought about how to achieve that. There seems to be no way to trap another process from outside and just let it stop the regular way.
Maybe it would be possible to use SetExcept() and then send a signal to the slave once gdb asks for stopping the program?
Problem is: this would end up in an exception handler in the slave, and the PC would not actually point to the debugee's regular code. The original PC is surely stored in the 'context' that is supposed to be stored on stack right before the exception handler gets called. Unfortunately, this context is not documented, so I wouldn't know how to extract the PC from there.
But if we had access to that context information, one could set up a trap in the exception handler to stop the debugee in the regular fashion.

Another way  would be to peek into Exec's task list (or precisely where it stores the context information). If we had access to that, one could plant a trap into the next debugee instruction and stop it that way. But I don't think the process context information is  available, is it?

**Comment by bebbo** [comment]
the first step: what is sent from gdb to gdbserver, if CTRL+C is pressed...

... If there is a command, I can work with it.

**Comment by mheyer32** [comment]
Printing the received commands in bgdbserver, it looks like gdb is sending
`:<$c>`

**Comment by mheyer32** [comment]
Disclaimer: I'm using the QtCreator IDE to do the debugging

**Comment by mheyer32** [comment]
This will also help adding breakpoints at runtime tremendously, as the debugger first attempts to interrupt the executable. As of today, I can't insert breakpoints while the program is running - which is a real PITA.

**Comment by bebbo** [comment]
please test

**Comment by mheyer32** [comment]
Doesn't seem to work. I attempted to interrupt ADoom - no dice.
![image](https://user-images.githubusercontent.com/33539855/59571688-314c8480-905c-11e9-8f5d-4e16463c1971.png)

The debugger (this time I tried from console, just regular m68k-amigaos-gdb) claims that

```
 ^C
The target is not responding to interrupt requests.
Stop debugging it? (y or n) n
```

**Comment by mheyer32** [comment]
ScummVM won't be interrupted either :-(

**Comment by bebbo** [comment]
please test again

**Comment by mheyer32** [comment]
Oh, of course I forgot to mention that I have an FPU in the system. Will test tonight :-)

**Comment by mheyer32** [comment]
Still doesn't work for me. Any more information I can provide?
It looks like the trap just gets inserted at the wrong place... the debugee just never stops.

**Comment by bebbo** [comment]
what system?
 - CPU
 - FPU
 - Kickstart

**Comment by bebbo** [comment]
It's working for me with 68040 and Kickstart 40.63

**Comment by bebbo** [comment]
II also testd 68020/68881 and 68030/68882 successfully
best bet: it's your kickstart

**Comment by mheyer32** [comment]
My 3.1 Kickstart is softkicked into RAM using Blizzard 1230-IV MapRom.

Maybe that is tripping up your ROM detection, because it is perhaps writeable?

**Comment by bebbo** [comment]
you could test without MapRom... 
... and if the ROM is writeable, breakpoints inside should work too.

I rather think, your ROM is using different code to save a thread's registers -> I need the precise version of your ROM (or your ROM^^)

**Comment by mheyer32** [comment]
Not being able to test right now, but I believe its 40.68 (A1200).
I'll check tonight if disabling MapRom makes any difference.

**Comment by mheyer32** [comment]
To answer your question more precisely:
WinUAE (didn't check real hw yet)
A1200 config
68030 + 68882
Blizzard 1230-IV, MapRom, 256MB
Kickstart 40.68 (I think...)
VBR + SSP in FastMem
I think I do have MMULib installed, but not sure if its in use.

**Comment by bebbo** [comment]
40.68 (A1200) is using the same code - and it's working here too.

**Comment by mheyer32** [comment]
Could other software like SetPatch, MCP, Executive throw in a monkey wrench?

**Comment by bebbo** [comment]
and it's funny to pause e.g. summvm via CTRL+C

=> experiment with your configuration!

**Comment by bebbo** [comment]
> 
> 
> Could other software like SetPatch, MCP, Executive throw in a monkey wrench?

It could by anything. Start with an empty s:startup-sequence^^ Mine is almost the original one.
And contains setpatch. winuaeenforcer does not hurt either.

**Comment by mheyer32** [comment]
My issues are connected to the use of BlizKick.

In particular the module "localfast" seem to be a culprit, maybe also "movevbr". "Localfast" moves exec.library to fastmem. When removing BlizKick from the startup-sequence, I was eventually able to stop the debugged process. Its a bit flaky, though. The callstack does not make sense in many cases (I can understand that, especially when attempting to stop in the middle of a system call - no stack frame there to follow). Sometimes it would just crash bgdbserver (or trip WinUAEEnforcer).

What is weird, though: when I could not break due to localfast, I didn't see anything else bad happening either.

Thinking about it: Its probably not a good idea to plant a trap into exec or any other library, because once the trap is set, random processes can trip over it, not just the one you'd like to debug. And they probably  don't even have a trap handler. Would it be possible to patch all processes to trap into bgdbserver's traphandler? Or is that evil :-)

Or maybe bgdbserver needs to build up a 'memory map' with exclusion zones where it cannot set traps.

I also wonder if it was somehow possible to detect library calls.... but in that case the m68k-amigaos-gdb needs to be beefed up to be able to even understand an in-library address (maybe we can build fake object files for libraries that provide debug symbols?!)

**Comment by bebbo** [comment]
All tools moving the kickstart to another location without write protecting that new location won't work.

There is no reason to use those tools while debugging. And there is no reason to use such tools in WinUAE at all.

Adding the trap handler to all programs won't work, since the debugee starts with a special pre startup which is missing there.

Keeping-track-of or detecting anything is much too elaborate.

I can add a check if the breakpoint is inside the program's segments. That's it. Since it works with the correct setup.

**Comment by mheyer32** [comment]
The updated version also works in my setup :-) Much more reliable!

The reason I have this setup is that I pulled the whole harddrive image from the actual machine and wanted to keep the setup as close as possible to each other.
